name = "berbegue-22"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "2da1f3cc37f745d8af7cc0d8ac6c87a8"

[build]
command = "cargo install worker-build@^0.1 && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build@^0.1 && worker-build --dev" }

[vars]
UUID = "a4e85535-1c99-47d3-b036-6a471ecfb1cf"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/hounna19/babi/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/hounna19/babi/refs/heads/main/web/sub.html"
